---
title: "Data Manipulation"
author: "Manye Dong"
date: "2023-09-21"
output: html_document
---

```{r}
library(tidyverse)
```
```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

```{r}
select(litters_data, group:gd_of_birth)
```

```{r}
select(litters_data, -starts_with("gd"))
```
```{r}
select(litters_data, litter_number, pups_survive, everything())
# everything means, in the end, I want to keep everything in my data
```

```{r}
pups_data
```

```{r}
select(pups_data, litter_number, sex, pd_ears)
```
```{r}
filter(litters_data, group %in% c("Con7", "Con8"))
filter(litters_data, group == "Con7" | gd_of_birth == 20)
```
```{r}
# Filter to include only pups with sex 1
# Filter to include only pups with PD walk less than 11 and sex 2
filter(pups_data, sex==1)
filter(pups_data, sex==2 & pd_walk<11)
```
```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```
```{r}
mutate(pups_data, pivot_minus7 = pd_pivot - 7)
```
```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") |> 
  janitor::clean_names() |> 
  select(-pups_survive) |> 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) |> 
  drop_na(wt_gain)

litters_data
```

